INSERT INTO "categories" ("id", "name", "type") VALUES
  (gen_random_uuid(), 'Moradia', 'expense'),
  (gen_random_uuid(), 'Alimentação', 'expense'),
  (gen_random_uuid(), 'Transporte', 'expense'),
  (gen_random_uuid(), 'Saúde', 'expense'),
  (gen_random_uuid(), 'Educação', 'expense'),
  (gen_random_uuid(), 'Lazer', 'expense'),
  (gen_random_uuid(), 'Assinaturas', 'expense'),
  (gen_random_uuid(), 'Vestuário', 'expense'),
  (gen_random_uuid(), 'Utilidades', 'expense'),
  (gen_random_uuid(), 'Luz', 'expense'),
  (gen_random_uuid(), 'Água', 'expense'),
  (gen_random_uuid(), 'Gás', 'expense'),
  (gen_random_uuid(), 'Condomínio', 'expense'),
  (gen_random_uuid(), 'Internet', 'expense'),
  (gen_random_uuid(), 'Seguros', 'expense'),
  (gen_random_uuid(), 'Academia', 'expense'),
  (gen_random_uuid(), 'Games', 'expense'),
  (gen_random_uuid(), 'Suplementos', 'expense'),
  (gen_random_uuid(), 'Contas Domésticas', 'expense'),
  (gen_random_uuid(), 'Salário', 'income'),
  (gen_random_uuid(), 'Freela', 'income'),
  (gen_random_uuid(), 'Investimentos', 'income'),
  (gen_random_uuid(), 'Outros', 'income');
